# Site
repository: sproogen/resume-theme
favicon: images/favicon.png

# Content configuration version
version: 2

# Personal info
name: Courtney L. Hatch
title: Data & Analytics Manager
email: hatch.courtney@gmail.com
website: courtneyhatch.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: courtneylorraine
github_username:  halfcourt
# instagram_username: courtneylorraine
linkedin_username: courtneylhatch

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
 gtag: "G-7H96R9K7MY"
# google_analytics: "UA-259298847-0"

# About Section
# about_title: About Me
about_profile_image: images/profile_ch.jpeg
about_content: | # this will include new lines to allow paragraphs
  I am a Harvard Business Analytics Graduate & Ambassador. I enjoy working on initiatives that enhance existing operational capabilities as well as explore new innovative ways to optimize processes for future value creation.

  My primary experience is working with B2B Marketing data, but I am always open to explore new areas of growth through data analysis. 

  I am a firm believer that Marketing's process and data can provide more value to an organization than generally perceived, and that business operations who choose to enable and leverage this data for insight and growth will ultimately succeed. 

  I am most skilled in: <mark>Laughing</mark> <mark>Eating</mark> <mark>Asking Questions</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/halfcourt
        # link_text: Project Website
        additional_links:
          # - title:  sproogen/modern-resume-theme
          #  icon: fab fa-github
          #  url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #  This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          Description text goes here.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Verizon Media
        link: verizondigitalmedia.com
        # link_text: verizondigitalmedia.com
        sub_title: Data & Analytics Manager, Marketing
        caption: December 2020 - Present
        quote: >
          Something clever clever goes here
        description: | # this will include new lines to allow paragraphs
            Description text goes here.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvard Business Analytics Program
        caption: January 2019 - March 2020
        sub_title: Certification
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Description text goes here.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in data and analytics some of my other interests and hobbies are:
      - Thing 1
      - Thing 2
      - Thing 3


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
